StylesPath = .vale/styles

MinAlertLevel = suggestion

# Here's were we define the exceptions to use in *all*
# `BasedOnStyles`.
Vocab = Galileo-Vocab

[*.{md}]
# ^ This section applies to only Markdown files.
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale
