StylesPath = .vale/styles

MinAlertLevel = suggestion

# Here's were we define the exceptions to use in *all*
# `BasedOnStyles`.
Vocab = Galileo-Vocab

Packages = MDX

; [formats]
; mdx = md

[*.mdx]
BasedOnStyles = Vale
; BlockIgnores = `[^`]+`
; TokenIgnores = (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)

; [*.mdx]
; CommentDelimiters = {/*, */}

